# This file was generated by GoReleaser. DO NOT EDIT.
cask "nginx-prometheus-exporter" do
  name "nginx-prometheus-exporter"
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://github.com/nginx/nginx-prometheus-exporter"
  version "1.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nginx-prometheus-exporter"
  manpage "manpages/nginx-prometheus-exporter.1.gz"
  bash_completion "completions/nginx-prometheus-exporter.bash"
  zsh_completion "completions/nginx-prometheus-exporter.zsh"

  on_macos do
    on_intel do
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v#{version}/nginx-prometheus-exporter_#{version}_darwin_amd64.tar.gz"
      sha256 "860884b6e240595c81848c1f04ac1af7460b05b1e852d28d845aa64375a3c030"
    end
    on_arm do
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v#{version}/nginx-prometheus-exporter_#{version}_darwin_arm64.tar.gz"
      sha256 "3b9c62f36e14278f849172f9dfca0412c14466076de0259020db5c91cac8870c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v#{version}/nginx-prometheus-exporter_#{version}_linux_amd64.tar.gz"
      sha256 "42ddc7ac31c70021d2a5c10414d473526490769632c1ef430b95d76dd1e3c187"
    end
    on_arm do
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v#{version}/nginx-prometheus-exporter_#{version}_linux_arm64.tar.gz"
      sha256 "8bea88fe912c63791de1fd35c8829f89c2e18b87fdb001c9b65fc371b2ebef3c"
    end
  end

  # No zap stanza required
end
