# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxPrometheusExporter < Formula
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://github.com/nginx/nginx-prometheus-exporter"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.5.0/nginx-prometheus-exporter_1.5.0_darwin_amd64.tar.gz"
      sha256 "5768462168690df12ddea6cf9a19007704362903fe91d83adfe4bee8a8a32656"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.5.0/nginx-prometheus-exporter_1.5.0_darwin_arm64.tar.gz"
      sha256 "de1b27e8069189146dacee9a009b85bbe7fa14752b60c721446158b9111a0881"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.5.0/nginx-prometheus-exporter_1.5.0_linux_amd64.tar.gz"
        sha256 "2614e4d18a181bee5828303df25a205f67449b6cb2de7b0ddfe1284a1f83e1df"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.5.0/nginx-prometheus-exporter_1.5.0_linux_armv6.tar.gz"
        sha256 "6b9ba9c19b1d14d40b5f3b2515618ab475db15ac7ee8b89b103729e921f1e82a"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.5.0/nginx-prometheus-exporter_1.5.0_linux_arm64.tar.gz"
        sha256 "2c4bba91470215623fe077d6256680e4bce51cc291bc4027b5efc2992e8cc5e0"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
  end
end
