# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxPrometheusExporter < Formula
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://github.com/nginx/nginx-prometheus-exporter"
  version "1.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.1/nginx-prometheus-exporter_1.4.1_darwin_amd64.tar.gz"
      sha256 "871d863a5fa561f46812bc0d96582c51171481d72ecfc12df410ed7b475b3dca"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.1/nginx-prometheus-exporter_1.4.1_darwin_arm64.tar.gz"
      sha256 "9f6cd277fc9a7ed57398c08ecb34fc8f1a06521a8399f0f20e5f14cb695e68a7"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.1/nginx-prometheus-exporter_1.4.1_linux_amd64.tar.gz"
        sha256 "2708d900fea0666aa5de0397c850ccfe0c11449c7ea75cc8534d7478ba8adce9"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.1/nginx-prometheus-exporter_1.4.1_linux_armv6.tar.gz"
        sha256 "24013af08abe3b7782e5d3a68963b89ee1418a7a86e5eb87f00a7d6954424bf5"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.1/nginx-prometheus-exporter_1.4.1_linux_arm64.tar.gz"
        sha256 "3f34c808bcf74cb965a7b91d072b54112dc22ed0d8f7599c7d85742c810cb73c"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
  end
end
