# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxPrometheusExporter < Formula
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://github.com/nginx/nginx-prometheus-exporter"
  version "1.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.2/nginx-prometheus-exporter_1.4.2_darwin_amd64.tar.gz"
      sha256 "b417914aa8cf81faa0d07629089e126eb28d9ae4fc0dd322fa543a783788a67e"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.2/nginx-prometheus-exporter_1.4.2_darwin_arm64.tar.gz"
      sha256 "9de1c1dadb476d8cb391d82e7a1318d575abf6703bd37c576b387b4d2cd1e7d3"

      def install
        bin.install "nginx-prometheus-exporter"
        bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
        zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
        man1.install "manpages/nginx-prometheus-exporter.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.2/nginx-prometheus-exporter_1.4.2_linux_amd64.tar.gz"
        sha256 "382125866a1dc4ae6ac5355bb462040a7f0d96d9d1bd59658c2d5f80b49e3da6"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.2/nginx-prometheus-exporter_1.4.2_linux_armv6.tar.gz"
        sha256 "9c92de19a40e60c64a7b469ed360c9479bee2086ff9a9463c474b792224b9d5c"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v1.4.2/nginx-prometheus-exporter_1.4.2_linux_arm64.tar.gz"
        sha256 "649c730e3ab79b6f5228a4dadde0ba1b59cedaafc4a9e38b9de2c7e14a2a9cf6"

        def install
          bin.install "nginx-prometheus-exporter"
          bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
          zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
          man1.install "manpages/nginx-prometheus-exporter.1.gz"
        end
      end
    end
  end
end
